### ISSUE TITLE
nedelujoč regularni izraz

### ISSUE THREAD

**Issue by Petja-Murnik** [Petja-Murnik/APPR-2021-22#1]
V vrstici 76 in 77 v datoteki `uvoz.r` regularni izraz ne spremeni pravilno če uporabim regularni izraz `"(\\d{0,8}\\s*)([a-zčšžA-ZČŠŽ ]+)(/*[a-zčšžA-ZČŠŽ ]*)$" ` ne spremeni pravilno da bi lahko spremenil 090007 Portorož/Portorose v Portorož . Regularni izraz, ki je sedaj uporabljen kot `vzorec_preb` deluje pravilno na vseh ostalih primerih razen na primeru Portoroža.

**Comment by evadezelak** [comment]
Meni regularni izraz, ki ga imaš sedaj zakomentiranga dela tudi za primer Portoroža, tako da ti težko povem, zakaj pri tebi ne dela. Lahko pa bi to rešil na ta način: najprej narediš regularni izraz, ki ti odstrani samo številke (torej v primeru Portoroža bi ti ostalo Portorož/Portorose), nato pa narediš še en regularni izraz, da dobiš ven samo Portorož.
