### ISSUE TITLE
Kako pobarvati font v zemljevidu?

### ISSUE THREAD

**Issue by Petja-Murnik** [Petja-Murnik/APPR-2021-22#3]
Pri vizualizaciji na zemljevidu v datoteki `vizualizacija.r` od vrstic 79 do 100 imam narisan graf g12 . V njem imam podatek od Jesenic, ki je napoved iz `analiza.r` . Zemljevid bi imel rad tak kot ga imam sedaj, le da bi bilo font od "Jesenic" pobarvan rdeče , font vseh ostalih naselij bi pa ostal črn.

**Comment by Petja-Murnik** [comment]
g12 se po novem nahaja v `analiza.r` od vrstice  127 naprej

**Comment by katarinabrilej** [comment]
Najenostavnejše je, če dvakrat dodaš tekst - enkrat za Jesenice in enkrat za vse preostale občine.
```
  geom_text(
    data = data_12 %>% filter(naselje != "Jesenice"),
    mapping = aes(x = lon , y = lat+0.07, label = naselje),
    size = 2.5
  ) + 
  geom_text(
    data = data_12 %>% filter(naselje == "Jesenice"),
    mapping = aes(x = lon , y = lat+0.07, label = naselje),
    size = 2.5 ,colour = "red"
  )
```
